### ISSUE TITLE
"component page" link returns a 404

### ISSUE THREAD

**Issue by jeffposnick** [googlearchive/prettify-element#1]
The "component page" link in the project's README points to http://polymer.github.io/prettify-element, which returns a 404.

It's difficult to use the element without a working link to the JSDoc or viewing the live demo.html.

**Comment by davidmaxwaterman** [comment]
Any news on this?

**Comment by sjmiles** [comment]
Fixed.

**Comment by sjmiles** [comment]
For the record, note that if you download/checkout/bower install an element, loading the `index.html` from the element folder should render the same page that appears on the `github.io` version. You have to load the page from a web server, and must also have the necessary dependencies (which is handled by Bower usually).

**Comment by davidmaxwaterman** [comment]
Good tip, thanks!
